output_prefix: "work"
leveled:
  batteries:
    - battery_1
  sites:
    - 30
    - 40
    - 50
    - 60
    - 70

robust:
  seeds:
    - 1
    - 2
    - 3
    - 4
  validationSeeds:
    - 11
    - 12
    - 13
    - 21
    - 22
    - 23
    - 31
    - 32
    - 33
    - 41
    - 42
    - 43
    - 51
    - 52
    - 53
    - 61
    - 62
    - 63
    - 71
    - 72
    - 73
    - 81
    - 82
    - 83

  groups:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
