configfile: "config.yaml"
OUTPUT_PREFIX = config["output_prefix"]
include: "common.smk"
include: "BuildBinaries.smk"
include: "Preprocessing.smk"
include: "PerformanceScenarios.smk"
include: "Robust.smk"
include: "RealCase.smk"
include: "TechCase.smk"

import numpy as np

RC_SEN_RANGE = ["{:.2f}".format(i) for i in np.arange (0.5, 1.5, 0.05)]
#RC_SEN_RANGE=["0.50", "0.60", "0.70","0.80", "0.85","0.90","0.95","1.00","1.05","1.10","1.15", "1.20", "1.30","1.40", "1.50" ]

RC_DAY_RANGE=["{:02}".format(i) for i in range(1,31 +1) ]

APRIORI_RANGE = ["{:.2f}".format(i) for i in np.arange (0.1, 3.0, 0.1)]

rule robust_methods:
    input:
         ## PERFORMANCE SCENARIOS
          expand(OUTPUT_PREFIX + "/opt/{SEED}/group_{TYPE_GROUP}/battery_1/tol00/{NUM_SITES}/{NUM_VEHICLES}/{OUTPUT_FILE}",
                     SEED = [1,2,3,4],
                     TYPE_GROUP = [0,1,2,3,4,5,6],
                     NUM_SITES = [60],
                     NUM_VEHICLES = list(map(lambda x : x * 100,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])),
                     OUTPUT_FILE = ["opt_log","active_sites", "input_feasible"]
                 ),


          expand(OUTPUT_PREFIX + "/opt/{SEED}/group_{TYPE_GROUP}/battery_1/tol00/{NUM_SITES}/{NUM_VEHICLES}/{OUTPUT_FILE}",
                     SEED = [1,2,3,4],
                     TYPE_GROUP = [0,1,2,3,4,5,6],
                     NUM_SITES = [20,25,30,35,40,45,50,55,60,65,70],
                     NUM_VEHICLES = [1000,500],
                     OUTPUT_FILE = ["opt_log","active_sites", "input_feasible"]
                 ),
# instance_stats
          expand( OUTPUT_PREFIX + "/preprocessed/{SEED}/group_{TYPE_GROUP}/{NUM_SITES}/{NUM_VEHICLES}/{BATTERY}.stats.txt",
                  SEED = [1,2,3,4],
                  TYPE_GROUP = [0,1,2,3,4,5,6],
                  NUM_SITES = [60,30],
                  NUM_VEHICLES = [1000,500],
                  BATTERY = ["battery_1"]
          ),             
# table
          expand(OUTPUT_PREFIX + "/opt/{SEED}/group_{TYPE_GROUP}/battery_1/tol00/{NUM_SITES}/{NUM_VEHICLES}/{OUTPUT_FILE}",
                     SEED = [1,2,3,4],
                     TYPE_GROUP = [0,1,2,3,4,5,6],
                     NUM_SITES = [30,40,50,60,70],
                     NUM_VEHICLES = list(map(lambda x : x * 100,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])),
                     OUTPUT_FILE = ["opt_log","active_sites", "input_feasible"]
                 ),
         ## ROBUST SCENARIOS
             #FULL
             expand(OUTPUT_PREFIX +  "/opt/robust/battery_1/60/{NUM_VEHICLES}/full_{OUTPUT_FILE}_quorum:{QUORUM}",
                 QUORUM=[100,99,98,97,96,95,94,93,92,91,90,80],
                 OUTPUT_FILE=["opt_log","percent_feasible"],
                 NUM_VEHICLES = [500,1000]
                ),


             expand(OUTPUT_PREFIX + "/opt/robust/battery_1/60/{NUM_VEHICLES}/{TYPE}_{OUTPUT_FILE}_tol00",
             TYPE=["median","lowest"],
             NUM_VEHICLES = [500,1000],
             OUTPUT_FILE=["opt_log","percent_feasible"]),

             expand(OUTPUT_PREFIX +  "/opt/robust/battery_1/60/{NUM_VEHICLES}/{TYPE}_{OUTPUT_FILE}_quorum:{QUORUM}_activate:1_benevolent:{BENEVOLENT}_iis:{IIS}",
                TYPE=["median","lowest"],
		        QUORUM=[100],
                BENEVOLENT=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
                IIS=["true"],
                OUTPUT_FILE=["opt_log","percent_feasible","active_sites"],
                NUM_VEHICLES = [500,1000]
            ),
            # comparions iis vs not iis
             expand(OUTPUT_PREFIX +  "/opt/robust/battery_1/60/{NUM_VEHICLES}/{TYPE}_{OUTPUT_FILE}_quorum:{QUORUM}_activate:1_benevolent:{BENEVOLENT}_iis:{IIS}",
                            TYPE=["median","lowest"],
            		        QUORUM=[100],
                            BENEVOLENT=[5,10],
                            IIS=["false","true"],
                            OUTPUT_FILE=["opt_log","percent_feasible","active_sites"],
                            NUM_VEHICLES = [500,1000]
                ),

             ## a-postori
             expand(OUTPUT_PREFIX +  "/opt/robust/battery_1/60/1000/full_validation_cross_feasibility_quorum:{QUORUM}",
                    QUORUM=[100,99,98,97,96,95,94,93,92,91,90,80]
             ),
             expand(OUTPUT_PREFIX +  "/opt/robust/battery_1/60/1000/{TYPE}_validation_cross_feasibility_quorum:100_activate:1_benevolent:{BENEVOLENT}_iis:true",
                    TYPE=["median","lowest"],
                    BENEVOLENT=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
             ),


        ## SAME COSTS
          expand(OUTPUT_PREFIX +  "/opt/robust/battery_1/60_samecosts/{NUM_VEHICLES}/{TYPE}_{OUTPUT_FILE}_quorum:100_activate:1_benevolent:{BENEVOLENT}_iis:{IIS}",
                TYPE=["lowest"],
                BENEVOLENT=[5],
                IIS=["true"],
                OUTPUT_FILE=["opt_log","percent_feasible","active_sites"],
                NUM_VEHICLES = [500,1000]
            ),
          expand(OUTPUT_PREFIX + "/opt/{SEED}/group_{TYPE_GROUP}/battery_1/tol00/{NUM_SITES}/{NUM_VEHICLES}/{OUTPUT_FILE}",
                     SEED = [1,2,3,4],
                     TYPE_GROUP = [0,1,2,3,4,5,6],
                     NUM_SITES = ["60_samecosts"],
                     NUM_VEHICLES = [1000,500],
                     OUTPUT_FILE = ["opt_log","active_sites"]
                 ),
        ## Realcase
#          expand(
#                OUTPUT_PREFIX + "/opt/realcase/robust/dbat:{DBAT}_dcha:{DCHAR}_dfin:{DFINAL}/{TYPE}_{OUTPUT_FILE}_quorum:{QUORUM}_activate:1_benevolent:{BENEVOLENT}_iis:{IIS}",
#                IIS=["true"],
#                TYPE=["lowest"],
#                QUORUM=[100],
#                BENEVOLENT=[5],
#                OUTPUT_FILE=["opt_log","percent_feasible","active_sites"],
#                DBAT=RC_SEN_RANGE,
#                DCHAR=["1.00"],
#                DFINAL=["1.00"]
#            ),
#          expand(
#                OUTPUT_PREFIX + "/opt/realcase/robust/dbat:{DBAT}_dcha:{DCHAR}_dfin:{DFINAL}/{TYPE}_{OUTPUT_FILE}_quorum:{QUORUM}_activate:1_benevolent:{BENEVOLENT}_iis:{IIS}",
#                IIS=["true"],
#                TYPE=["lowest"],
#                QUORUM=[100],
#                BENEVOLENT=[5],
#                OUTPUT_FILE=["opt_log","percent_feasible","active_sites"],
#                DBAT=["1.00"],
#                DCHAR=RC_SEN_RANGE,
#                DFINAL=["1.00"]
#            ),
#          expand(
#                OUTPUT_PREFIX + "/opt/realcase/robust/dbat:{DBAT}_dcha:{DCHAR}_dfin:{DFINAL}/{TYPE}_{OUTPUT_FILE}_quorum:{QUORUM}_activate:1_benevolent:{BENEVOLENT}_iis:{IIS}",
#                IIS=["true"],
#                TYPE=["lowest"],
#                QUORUM=[100],
#                BENEVOLENT=[5],
#                OUTPUT_FILE=["opt_log","percent_feasible","active_sites"],
#                DBAT=["1.00"],
#                DCHAR=["1.00"],
#                DFINAL=RC_SEN_RANGE
#            ),
#
#
#
# apriori-cross_feasibility
            expand(
                    OUTPUT_PREFIX + "/preprocessed/group_{GROUP}/215/dbat:{DBAT}_dcha:{DCHAR}_dfin:{DFINAL}.feasible.vehicles.csv.gz.count",
                    DBAT=APRIORI_RANGE,
                    DCHAR=APRIORI_RANGE,
                    DFINAL=["1.00"],
                    GROUP=[0,1,2,3,4,5,6]
            ),


            # # techcase
            # expand(
            #     OUTPUT_PREFIX + "/opt/techcase/robust/60/500/dbat:{DBAT}_dcha:{DCHAR}_dfin:{DFINAL}/full_{OUTPUT_FILE}_quorum:100",
            #     DBAT=RC_SEN_RANGE,
            #     DCHAR=["1.00"],
            #     DFINAL=["1.00"],
            #     OUTPUT_FILE=["opt_log", "cross_feasibility", "percent_feasible"],
            # ),
            # expand(
            #     OUTPUT_PREFIX + "/opt/techcase/robust/60/500/dbat:{DBAT}_dcha:{DCHAR}_dfin:{DFINAL}/full_{OUTPUT_FILE}_quorum:100",
            #     DBAT=["1.00"],
            #     DCHAR=RC_SEN_RANGE,
            #     DFINAL=["1.00"],
            #     OUTPUT_FILE=["opt_log", "cross_feasibility", "percent_feasible"],
            # ),
            # expand(
            #     OUTPUT_PREFIX + "/opt/techcase/robust/60/500/dbat:{DBAT_CHAR}_dcha:{DBAT_CHAR}_dfin:{DFINAL}/full_{OUTPUT_FILE}_quorum:100",
            #     DBAT_CHAR=RC_SEN_RANGE,
            #     DFINAL=["1.00"],
            #     OUTPUT_FILE=["opt_log", "cross_feasibility", "percent_feasible"],
            # ),
            # expand(
            #     OUTPUT_PREFIX + "/opt/techcase/robust/60/500/dbat:{DBAT}_dcha:{DCHAR}_dfin:{DFINAL}/full_{OUTPUT_FILE}_quorum:100",
            #     DBAT=["1.00"],
            #     DCHAR=["1.00"],
            #     DFINAL=RC_SEN_RANGE,
            #     OUTPUT_FILE=["opt_log", "cross_feasibility", "percent_feasible"],
            # ),
            
            #  expand(
            #     OUTPUT_PREFIX + "/opt/techcase/robust/60/500/dbat:{DBAT}_dcha:{DCHAR}_dfin:{DFINAL}/{TYPE}_{OUTPUT_FILE}_quorum:{QUORUM}_activate:1_benevolent:{BENEVOLENT}_iis:{IIS}",
            #     IIS=["true"],
            #     TYPE=["lowest"],
            #     QUORUM=[100],
            #     BENEVOLENT=[5],
            #     OUTPUT_FILE=["opt_log","percent_feasible","active_sites"],
            #     DBAT=RC_SEN_RANGE,
            #     DCHAR=["1.00"],
            #     DFINAL=["1.00"]
            # ),
            # expand(
            #     OUTPUT_PREFIX + "/opt/techcase/robust/60/500/dbat:{DBAT}_dcha:{DCHAR}_dfin:{DFINAL}/{TYPE}_{OUTPUT_FILE}_quorum:{QUORUM}_activate:1_benevolent:{BENEVOLENT}_iis:{IIS}",
            #     IIS=["true"],
            #     TYPE=["lowest"],
            #     QUORUM=[100],
            #     BENEVOLENT=[5],
            #     OUTPUT_FILE=["opt_log","percent_feasible","active_sites"],
            #     DBAT=["1.00"],
            #     DCHAR=RC_SEN_RANGE,
            #     DFINAL=["1.00"]
            # ),
            # expand(
            #     OUTPUT_PREFIX + "/opt/techcase/robust/60/500/dbat:{DBAT_CHAR}_dcha:{DBAT_CHAR}_dfin:{DFINAL}/{TYPE}_{OUTPUT_FILE}_quorum:{QUORUM}_activate:1_benevolent:{BENEVOLENT}_iis:{IIS}",
            #     IIS=["true"],
            #     TYPE=["lowest"],
            #     QUORUM=[100],
            #     BENEVOLENT=[5],
            #     OUTPUT_FILE=["opt_log","percent_feasible","active_sites"],
            #     DBAT_CHAR=RC_SEN_RANGE,
            #     DFINAL=["1.00"]
            # ),
            # expand(
            #     OUTPUT_PREFIX + "/opt/techcase/robust/60/500/dbat:{DBAT}_dcha:{DCHAR}_dfin:{DFINAL}/{TYPE}_{OUTPUT_FILE}_quorum:{QUORUM}_activate:1_benevolent:{BENEVOLENT}_iis:{IIS}",
            #     IIS=["true"],
            #     TYPE=["lowest"],
            #     QUORUM=[100],
            #     BENEVOLENT=[5],
            #     OUTPUT_FILE=["opt_log","percent_feasible","active_sites"],
            #     DBAT=["1.00"],
            #     DCHAR=["1.00"],
            #     DFINAL=RC_SEN_RANGE
            # ),
   
              
